### PR TITLE
Fixes for 2023.1.1 

### PR DESCRIPTION
**Pull request by asaccool**
https://pharmaledger.atlassian.net/browse/EPI-403

### CODE REVIEW

**Comment by salboaie** [comment]
Fixes for all backup and restore issues (force button failing to work because of readWrite misspelt word, wrong selection of messages current causing buttons doing nothing because of undefined objects  and preventing unnecessary confirmation dialogues during restore) 
Fixing:
https://pharmaledger.atlassian.net/browse/EPI-401
https://pharmaledger.atlassian.net/browse/EPI-402
summarised in the change request associated with  https://pharmaledger.atlassian.net/browse/EPI-403

**Review by salboaie — APPROVED** [review]

**Comment by PL-James** [comment]
Tagging [ITSM-2] prior to review as the implementing change control for this PR.

[ITSM-2]: https://pharmaledger.atlassian.net/browse/ITSM-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by PL-Marco — APPROVED** [review]
All changes are related to backup and restore. Fixing the issue with read/write access for the Forced Restore button and pop up messages. No impact on the core functionality of the backup and restore feature.

**Review by PL-James — APPROVED** [review]
LGTM QA Approved.

**Pull request merged**
